apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "%NAMESPACE%"
  name: %NAMESPACE%-client-config
data:
  SERVER_PORT: '%SERVER_PORT%'
  NGINX_PORT: '%NGINX_PORT%'
  SERVER_NAME: %NAMESPACE%-server.%NAMESPACE%
  CLIENT_AUTHORIZER_URL: 'https://sso.%SERVER_DOMAIN%'
  CLIENT_MINIO_URL: 'https://files.%SERVER_DOMAIN%'
  CLIENT_WEBHOOK_SUPER_ADMIN_EXTERNAL_USER_ID: '%CLIENT_WEBHOOK_SUPER_ADMIN_EXTERNAL_USER_ID%'

