/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AuthErrorEnumInterface = 'AUTH-000' | 'AUTH-001' | 'AUTH-002';

export const AuthErrorEnumInterface = {
  _000: 'AUTH-000' as AuthErrorEnumInterface,
  _001: 'AUTH-001' as AuthErrorEnumInterface,
  _002: 'AUTH-002' as AuthErrorEnumInterface,
};
