/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type FilesErrorEnumInterface = 'FILES-000' | 'FILES-001';

export const FilesErrorEnumInterface = {
  _000: 'FILES-000' as FilesErrorEnumInterface,
  _001: 'FILES-001' as FilesErrorEnumInterface,
};
