/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';
import { WebhookObjectInterface } from './webhook-object.interface';

export interface FindManyWebhookResponseInterface {
  webhooks: Array<WebhookObjectInterface>;
  meta: FindManyResponseMetaInterface;
}
