/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';
import { WebhookLogObjectInterface } from './webhook-log-object.interface';

export interface FindManyWebhookLogResponseInterface {
  webhookLogs: Array<WebhookLogObjectInterface>;
  meta: FindManyResponseMetaInterface;
}
