/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateWebhookArgsInterface {
  eventName?: string;
  endpoint?: string;
  enabled?: boolean;
  headers?: object;
  requestTimeout?: number;
}
