/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type WebhookErrorEnumInterface =
  | 'WEBHOOK-000'
  | 'WEBHOOK-001'
  | 'WEBHOOK-002'
  | 'WEBHOOK-003'
  | 'WEBHOOK-004'
  | 'WEBHOOK-005';

export const WebhookErrorEnumInterface = {
  _000: 'WEBHOOK-000' as WebhookErrorEnumInterface,
  _001: 'WEBHOOK-001' as WebhookErrorEnumInterface,
  _002: 'WEBHOOK-002' as WebhookErrorEnumInterface,
  _003: 'WEBHOOK-003' as WebhookErrorEnumInterface,
  _004: 'WEBHOOK-004' as WebhookErrorEnumInterface,
  _005: 'WEBHOOK-005' as WebhookErrorEnumInterface,
};
