version: '3'
networks:
  nestjs-mod-fullstack-network:
    driver: 'bridge'
services:
  nestjs-mod-fullstack-e2e-tests:
    image: 'ghcr.io/%E2E_TESTS_IMAGE_NAME%'
    container_name: 'nestjs-mod-fullstack-e2e-tests'
    networks:
      - 'nestjs-mod-fullstack-network'
    environment:
      SERVER_AUTHORIZER_AUTHORIZER_AUTHORIZER_URL: 'https://sso.%SERVER_DOMAIN%'
      SERVER_AUTHORIZER_MINIO_URL: 'https://files.%SERVER_DOMAIN%'
      E2E_CLIENT_URL: 'https://%SERVER_DOMAIN%'
      E2E_SERVER_URL: 'https://%SERVER_DOMAIN%'
      E2E_INTERNAL_SERVER_URL: 'https://%SERVER_DOMAIN%'
      SERVER_AUTHORIZER_AUTH_ADMIN_EMAIL: 'admin@site15.ru'
      SERVER_AUTHORIZER_AUTH_ADMIN_USERNAME: 'admin'
      SERVER_AUTHORIZER_AUTH_ADMIN_PASSWORD: '%SERVER_AUTH_ADMIN_PASSWORD%'
      SERVER_AUTHORIZER_AUTHORIZER_ADMIN_SECRET: '%SERVER_AUTHORIZER_ADMIN_SECRET%'
    working_dir: '/usr/src/app'
    volumes:
      - './../../apps:/usr/src/app/apps'
      - './../../libs:/usr/src/app/libs'
