version: '3'
networks:
  nestjs-mod-fullstack-network:
    driver: 'bridge'
services:
  nestjs-mod-fullstack-e2e-tests:
    image: 'ghcr.io/nestjs-mod/nestjs-mod-fullstack-e2e-tests:%ROOT_VERSION%'
    container_name: 'nestjs-mod-fullstack-e2e-tests'
    networks:
      - 'nestjs-mod-fullstack-network'
    environment:
      BASE_URL: 'https://%SERVER_DOMAIN%'
      CLIENT_URL: 'https://%SERVER_DOMAIN%'
      SERVER_AUTHORIZER_URL: 'https://sso.%SERVER_DOMAIN%'
      SERVER_MINIO_URL: 'https://files.%SERVER_DOMAIN%'
      SERVER_URL: 'https://%SERVER_DOMAIN%/api'
      SERVER_AUTH_ADMIN_EMAIL: 'admin@site15.ru'
      SERVER_AUTH_ADMIN_USERNAME: 'admin'
      SERVER_AUTH_ADMIN_PASSWORD: '%SERVER_AUTH_ADMIN_PASSWORD%'
      SERVER_AUTHORIZER_ADMIN_SECRET: '%SERVER_AUTHORIZER_ADMIN_SECRET%'
    working_dir: '/usr/src/app'
    volumes:
      - './../../apps:/usr/src/app/apps'
      - './../../libs:/usr/src/app/libs'
