kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: '%NAMESPACE%'
  name: %NAMESPACE%-redis-pv-claim
  labels:
    type: local
    app: %NAMESPACE%-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
