apiVersion: v1
kind: Service
metadata:
  namespace: "master"
  name: master-server
  labels:
    app: master-server
spec:
  selector:
    app: master-server
  ports:
    - name: '9191'
      protocol: TCP
      port: 9191
      targetPort: 9191
  type: ClusterIP
